import { Business, Category, Service, Booking, Review, User, Resource, BlockedTime, Notification, AuditLog } from '@/types';

export const DEHRADUN_NEIGHBORHOODS = [
  'All Areas',
  'Rajpur Road',
  'Jakhan',
  'Ballupur',
  'Vasant Vihar',
  'Race Course',
  'Sahastradhara Road',
  'Clock Tower',
  'Clement Town',
  'GMS Road',
  'Chakrata Road',
];

export const DEMO_USERS: User[] = [
  {
    id: 'usr-customer-gurpreet',
    name: 'Gurpreet Singh',
    email: 'gurpreet@bukkapp.in',
    phone: '+91 98765 43210',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'usr-owner-arjun',
    name: 'Dr. Arjun Verma',
    email: 'arjun@smilestudio.in',
    phone: '+91 98123 45678',
    role: 'business_owner',
    businessId: 'biz-smile-studio',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=150&q=80',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'usr-owner-rahul',
    name: 'Rahul Kapoor',
    email: 'rahul@zenithpickleball.in',
    phone: '+91 98999 11223',
    role: 'business_owner',
    businessId: 'biz-zenith-pickleball',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    createdAt: '2026-08-05T09:00:00Z',
  },
  {
    id: 'usr-admin-bukkapp',
    name: 'BUKKAPP Admin',
    email: 'ops@bukkapp.in',
    phone: '+91 11223 34455',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    createdAt: '2026-08-01T08:00:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'health-wellness',
    name: 'Health & Wellness',
    slug: 'health-wellness',
    description: 'Dentists, physiotherapy clinics, ayurvedic doctors, and medical consultants.',
    iconName: 'Activity',
    count: 8,
    popularServices: ['Dental Cleaning', 'Physio Consultation', 'Root Canal', 'Full Body Checkup'],
    active: true,
    sortOrder: 1,
  },
  {
    id: 'beauty-grooming',
    name: 'Beauty & Grooming',
    slug: 'beauty-grooming',
    description: 'Barbershops, boutique salons, luxury spas, and bridal styling studios.',
    iconName: 'Scissors',
    count: 7,
    popularServices: ['Signature Haircut', 'Beard Trim & Fade', 'Keratin Treatment', 'Facial & Glow'],
    active: true,
    sortOrder: 2,
  },
  {
    id: 'fitness-sports',
    name: 'Fitness & Sports',
    slug: 'fitness-sports',
    description: 'Pickleball courts, turf football, crossfit boxes, and badminton courts.',
    iconName: 'Activity',
    count: 6,
    popularServices: ['Pickleball Court (60m)', 'Turf Football (90m)', 'Badminton Court', 'Personal Training'],
    active: true,
    sortOrder: 3,
  },
  {
    id: 'home-services',
    name: 'Home Services',
    slug: 'home-services',
    description: 'AC maintenance, licensed electricians, master plumbers, and appliance repair.',
    iconName: 'Home',
    count: 6,
    popularServices: ['Split AC Deep Service', 'Electrical Inspection', 'Plumbing Diagnostics', 'Water Purifier RO'],
    active: true,
    sortOrder: 4,
  },
  {
    id: 'auto-care',
    name: 'Auto Care',
    slug: 'auto-care',
    description: 'Ceramic coating studios, detailing garages, foam wash, and bike servicing.',
    iconName: 'Wrench',
    count: 5,
    popularServices: ['Ceramic Shield 9H', 'Interior Deep Detail', 'Full Foam Wash', 'Wheel Alignment'],
    active: true,
    sortOrder: 5,
  },
];

export const SUBCATEGORY_PRESETS: Record<string, string[]> = {
  'health-wellness': [
    'Dental Clinic',
    'Physiotherapy & Rehab',
    'Ayurveda & Spa',
    'Diagnostic Lab & Pathology',
    'Mental Wellness & Therapy',
    'Eye Care & Optometry',
    'Dermatology & Skin Clinic',
    'Orthopedic & Spine Care',
    'Nutrition & Dietetics',
  ],
  'beauty-grooming': [
    'Men Grooming Lounge',
    'Unisex Salon',
    'Luxury Spa & Massage',
    'Nail & Lash Studio',
    'Bridal & Makeup Studio',
    'Skin & Aesthetic Clinic',
    'Hair Stylist & Color Bar',
    'Tattoo & Piercing Studio',
  ],
  'fitness-sports': [
    'Pickleball Arena',
    'Badminton & Squash Academy',
    'Turf Football / Cricket',
    'Crossfit Gym',
    'Yoga & Pilates Studio',
    'Swimming & Aquatic Club',
    'Strength & Fitness Gym',
    'Boxing & Martial Arts Academy',
  ],
  'home-services': [
    'AC & Appliance Care',
    'Electrician & Wiring',
    'Plumbing & Sanitation',
    'Home Cleaning & Deep Wash',
    'Pest Control & Disinfection',
    'Carpentry & Woodwork',
    'Painting & Waterproofing',
    'CCTV & Security Systems',
  ],
  'auto-care': [
    'Car Spa & Detailing',
    'Ceramic & PPF Studio',
    'Car Service & Mechanical',
    'Superbike & Two-Wheeler Care',
    'Wheel Alignment & Tyres',
    'Denting & Paint Studio',
    'Auto Electrical & Diagnostics',
  ],
};

export function getSubcategoryPresets(categoryId: string): string[] {
  return SUBCATEGORY_PRESETS[categoryId] || [
    'General Services',
    'Consultation & Diagnostics',
    'Premium Studio',
    'On-Site / Doorstep Service',
  ];
}

export const INITIAL_RESOURCES: Resource[] = [
  { id: 'res-zpc-c1', businessId: 'biz-zenith-pickleball', name: 'Court 1 (Pro Championship)', type: 'court', active: true },
  { id: 'res-zpc-c2', businessId: 'biz-zenith-pickleball', name: 'Court 2 (Cushioned Acrylic)', type: 'court', active: true },
  { id: 'res-zpc-c3', businessId: 'biz-zenith-pickleball', name: 'Court 3 (Covered All-Weather)', type: 'court', active: true },
  { id: 'res-ssd-chair1', businessId: 'biz-smile-studio', name: 'Operatory Chair 1', type: 'chair', active: true },
  { id: 'res-ssd-chair2', businessId: 'biz-smile-studio', name: 'Operatory Chair 2', type: 'chair', active: true },
];

export const INITIAL_BLOCKED_TIMES: BlockedTime[] = [
  {
    id: 'blk-1',
    businessId: 'biz-zenith-pickleball',
    startDatetime: '2026-08-25T13:00:00',
    endDatetime: '2026-08-25T14:30:00',
    reason: 'Court surface routine maintenance & cleaning',
    createdAt: '2026-08-20T10:00:00Z',
  },
];

const STANDARD_WEEK_SCHEDULE = [
  { dayOfWeek: 0, dayName: 'Sun', isOpen: true, openTime: '08:00', closeTime: '21:00', periods: [{ openTime: '08:00', closeTime: '21:00' }] },
  { dayOfWeek: 1, dayName: 'Mon', isOpen: true, openTime: '08:00', closeTime: '21:00', periods: [{ openTime: '08:00', closeTime: '13:00' }, { openTime: '16:00', closeTime: '21:00' }] },
  { dayOfWeek: 2, dayName: 'Tue', isOpen: true, openTime: '08:00', closeTime: '21:00', periods: [{ openTime: '08:00', closeTime: '21:00' }] },
  { dayOfWeek: 3, dayName: 'Wed', isOpen: true, openTime: '08:00', closeTime: '21:00', periods: [{ openTime: '08:00', closeTime: '21:00' }] },
  { dayOfWeek: 4, dayName: 'Thu', isOpen: true, openTime: '08:00', closeTime: '21:00', periods: [{ openTime: '08:00', closeTime: '21:00' }] },
  { dayOfWeek: 5, dayName: 'Fri', isOpen: true, openTime: '08:00', closeTime: '21:00', periods: [{ openTime: '08:00', closeTime: '21:00' }] },
  { dayOfWeek: 6, dayName: 'Sat', isOpen: true, openTime: '08:00', closeTime: '22:00', periods: [{ openTime: '08:00', closeTime: '22:00' }] },
];

export const INITIAL_BUSINESSES: Business[] = [
  // 1. FLAGSHIP DEMO BUSINESS: Zenith Pickleball Club
  {
    id: 'biz-zenith-pickleball',
    ownerId: 'usr-owner-rahul',
    name: 'Zenith Pickleball Club',
    slug: 'zenith-pickleball',
    tagline: 'Premier 3-Court Pickleball Arena in Dehradun with USAPA Standard Cushioned Turf',
    description: 'Dehradun premier pickleball venue featuring 3 tournament-spec courts, LED floodlights, paddle rentals, locker rooms, and certified coaching staff. Book courts in 60-minute blocks with instant confirmation.',
    categoryId: 'fitness-sports',
    categoryName: 'Fitness & Sports',
    subcategory: 'Pickleball Arena',
    address: 'Plot 14, Old Rajpur Road, Near Sai Mandir',
    neighborhood: 'Rajpur Road',
    city: 'Dehradun',
    state: 'Uttarakhand',
    country: 'India',
    postalCode: '248009',
    latitude: 30.3842,
    longitude: 78.0931,
    phone: '+91 98999 11223',
    email: 'play@zenithpickleball.in',
    website: 'https://zenithpickleball.in',
    instagram: 'zenithpickleball_ddn',
    coverImage: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 94,
    verified: true,
    status: 'active',
    startingPrice: 600,
    features: ['3 Tournament Courts', 'LED Floodlighting', 'Paddle & Ball Rentals', 'Locker & Showers', 'Free Parking', 'Pro Shop & Café'],
    schedule: STANDARD_WEEK_SCHEDULE,
    resources: INITIAL_RESOURCES.filter(r => r.businessId === 'biz-zenith-pickleball'),
    active: true,
    distanceKm: 1.1,
    nextAvailableSlot: 'Today, 6:00 PM',
    pageViewsThisWeek: 342,
    createdAt: '2026-08-05T09:00:00Z',
    updatedAt: '2026-08-22T10:00:00Z',
  },

  // 2. ACTIVE VERIFIED BUSINESS: Smile Studio Dental
  {
    id: 'biz-smile-studio',
    ownerId: 'usr-owner-arjun',
    name: 'Smile Studio Dental & Implant Center',
    slug: 'smile-studio-dental',
    tagline: 'Modern painless dentistry and advanced aesthetic smile makeovers in Jakhan',
    description: 'State-of-the-art dental clinic equipped with German digital radiography, painless ultrasonic scalers, and certified orthodontists.',
    categoryId: 'health-wellness',
    categoryName: 'Health & Wellness',
    subcategory: 'Dental Clinic',
    address: '42/1 Rajpur Road, Opp. Pacific Mall, Jakhan',
    neighborhood: 'Jakhan',
    city: 'Dehradun',
    state: 'Uttarakhand',
    country: 'India',
    postalCode: '248006',
    latitude: 30.3681,
    longitude: 78.0754,
    phone: '+91 98123 45678',
    email: 'contact@smilestudiodental.com',
    website: 'https://smilestudiodental.com',
    coverImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 148,
    verified: true,
    status: 'active',
    startingPrice: 500,
    features: ['Digital X-Rays', 'Painless Anesthesia', 'ISO Certified Sterilization', 'Air Conditioned', 'Ample Parking'],
    schedule: STANDARD_WEEK_SCHEDULE,
    active: true,
    distanceKm: 1.4,
    nextAvailableSlot: 'Today, 6:30 PM',
    pageViewsThisWeek: 215,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-22T10:00:00Z',
  },

  // 3. ACTIVE VERIFIED BUSINESS: The Groom Room
  {
    id: 'biz-the-groom-room',
    ownerId: 'usr-customer-gurpreet',
    name: 'The Groom Room & Barbershop',
    slug: 'the-groom-room',
    tagline: 'Precision fades, hot towel shaves, and beard craft in Ballupur',
    description: 'Upscale gentleman grooming studio offering bespoke haircuts, beard sculping, and relaxing scalp treatments.',
    categoryId: 'beauty-grooming',
    categoryName: 'Beauty & Grooming',
    subcategory: 'Men Grooming Lounge',
    address: '12 General Mahadev Singh Road, Ballupur Chowk',
    neighborhood: 'Ballupur',
    city: 'Dehradun',
    state: 'Uttarakhand',
    country: 'India',
    postalCode: '248001',
    latitude: 30.3342,
    longitude: 78.0211,
    phone: '+91 94111 22334',
    email: 'info@groomroomddn.com',
    coverImage: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 204,
    verified: true,
    status: 'active',
    startingPrice: 350,
    features: ['Master Stylists', 'Hot Towel Spa Shave', 'Single Malt Espresso Bar', 'Leather Recliners'],
    schedule: STANDARD_WEEK_SCHEDULE,
    active: true,
    distanceKm: 2.1,
    nextAvailableSlot: 'Today, 5:45 PM',
    pageViewsThisWeek: 184,
    createdAt: '2026-08-02T11:00:00Z',
    updatedAt: '2026-08-22T10:00:00Z',
  },

  // 4. PENDING REVIEW BUSINESS: Doon Ayurveda & Wellness
  {
    id: 'biz-doon-ayurveda',
    ownerId: 'usr-customer-gurpreet',
    name: 'Doon Ayurveda & Wellness Center',
    slug: 'doon-ayurveda',
    tagline: 'Authentic Panchakarma therapy and herbal consultations in Clement Town',
    description: 'Traditional Ayurvedic clinic offering pulse diagnosis (Nadi Pariksha), customized Panchakarma detox, and organic herbal medicines.',
    categoryId: 'health-wellness',
    categoryName: 'Health & Wellness',
    subcategory: 'Ayurveda & Spa',
    address: 'Post Office Road, Clement Town',
    neighborhood: 'Clement Town',
    city: 'Dehradun',
    state: 'Uttarakhand',
    country: 'India',
    postalCode: '248002',
    latitude: 30.2711,
    longitude: 78.0123,
    phone: '+91 98370 12345',
    email: 'info@doonayurveda.in',
    coverImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
    gallery: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80'],
    rating: 4.7,
    reviewCount: 32,
    verified: false,
    status: 'pending_review',
    startingPrice: 900,
    features: ['Certified Vaidyas', 'Authentic Kerala Oils', 'Private Therapy Suites'],
    schedule: STANDARD_WEEK_SCHEDULE,
    active: false,
    distanceKm: 5.4,
    pageViewsThisWeek: 45,
    createdAt: '2026-08-21T14:00:00Z',
    updatedAt: '2026-08-21T14:00:00Z',
  },

  // 5. NEEDS CHANGES BUSINESS: Jakhan Crossfit Box
  {
    id: 'biz-jakhan-crossfit',
    ownerId: 'usr-customer-gurpreet',
    name: 'Jakhan Crossfit Box & Training',
    slug: 'jakhan-crossfit',
    tagline: 'High-intensity functional fitness and Olympic lifting coaches in Jakhan',
    description: 'Dedicated functional training arena with Rogue rigs, bumper plates, rowing machines, and certified coaches.',
    categoryId: 'fitness-sports',
    categoryName: 'Fitness & Sports',
    subcategory: 'Crossfit Gym',
    address: 'Main Rajpur Road, Jakhan',
    neighborhood: 'Jakhan',
    city: 'Dehradun',
    state: 'Uttarakhand',
    country: 'India',
    postalCode: '248006',
    latitude: 30.3712,
    longitude: 78.0799,
    phone: '+91 98970 99887',
    email: 'train@jakhancrossfit.in',
    coverImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80',
    gallery: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80'],
    rating: 4.6,
    reviewCount: 18,
    verified: false,
    status: 'needs_changes',
    changeRequestReason: 'Please update your opening hours and upload at least 2 photos of the gym interior before publication.',
    startingPrice: 400,
    features: ['Rogue Equipment', 'Certified Coaches', 'Shower & Lockers'],
    schedule: STANDARD_WEEK_SCHEDULE,
    active: false,
    distanceKm: 1.8,
    pageViewsThisWeek: 60,
    createdAt: '2026-08-19T09:00:00Z',
    updatedAt: '2026-08-20T11:00:00Z',
  },

  // 6. SUSPENDED BUSINESS: City Glamour Salon
  {
    id: 'biz-city-glamour',
    ownerId: 'usr-customer-gurpreet',
    name: 'City Glamour Unisex Salon',
    slug: 'city-glamour-salon',
    tagline: 'Bridal makeover and styling studio at Clock Tower',
    description: 'Commercial salon suite offering express styling and bridal cosmetics.',
    categoryId: 'beauty-grooming',
    categoryName: 'Beauty & Grooming',
    subcategory: 'Unisex Salon',
    address: 'Paltan Bazaar Road, Clock Tower',
    neighborhood: 'Clock Tower',
    city: 'Dehradun',
    state: 'Uttarakhand',
    country: 'India',
    postalCode: '248001',
    latitude: 30.3244,
    longitude: 78.0418,
    phone: '+91 98970 11223',
    email: 'cityglamour@gmail.com',
    coverImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1200&q=80',
    gallery: ['https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80'],
    rating: 3.8,
    reviewCount: 42,
    verified: true,
    status: 'suspended',
    adminNotes: 'Suspended due to repeated customer complaints regarding off-platform pricing discrepancies.',
    startingPrice: 300,
    features: ['Bridal Suite', 'Hair Spa'],
    schedule: STANDARD_WEEK_SCHEDULE,
    active: false,
    distanceKm: 3.2,
    pageViewsThisWeek: 12,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-21T18:00:00Z',
  },

  // 7. ACTIVE: QuickCool AC Care
  {
    id: 'biz-quickcool-ac',
    ownerId: 'usr-customer-gurpreet',
    name: 'QuickCool AC & Appliance Care',
    slug: 'quickcool-ac',
    tagline: 'Doorstep AC jet pump service, gas charging, and PCB repairs across Dehradun',
    description: 'Certified HVAC technicians providing on-demand split & window AC repairs with genuine spare parts warranty.',
    categoryId: 'home-services',
    categoryName: 'Home Services',
    subcategory: 'AC & Appliance Care',
    address: 'Near Ballupur Flyover, Chakrata Road',
    neighborhood: 'Ballupur',
    city: 'Dehradun',
    state: 'Uttarakhand',
    country: 'India',
    postalCode: '248001',
    latitude: 30.3391,
    longitude: 78.0195,
    phone: '+91 98765 67890',
    email: 'support@quickcoolac.in',
    coverImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1200&q=80',
    gallery: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80'],
    rating: 4.8,
    reviewCount: 112,
    verified: true,
    status: 'active',
    startingPrice: 399,
    features: ['30-Day Service Guarantee', 'High Pressure Jet Wash', 'Uniformed Technicians', 'Digital Invoicing'],
    schedule: STANDARD_WEEK_SCHEDULE,
    active: true,
    distanceKm: 2.8,
    nextAvailableSlot: 'Today, 5:30 PM',
    pageViewsThisWeek: 165,
    createdAt: '2026-08-03T09:00:00Z',
    updatedAt: '2026-08-22T10:00:00Z',
  },

  // 8. ACTIVE: MotoGloss Detailing
  {
    id: 'biz-motogloss-detailing',
    ownerId: 'usr-customer-gurpreet',
    name: 'MotoGloss Studio & Ceramic Hub',
    slug: 'motogloss-detailing',
    tagline: 'Paint protection film, graphene coatings, and premium interior steam detailing',
    description: 'Precision auto aesthetics garage in Race Course with dust-free infrared curing bays.',
    categoryId: 'auto-care',
    categoryName: 'Auto Care',
    subcategory: 'Car Spa & Detailing',
    address: '18 Subhash Road, Near St. Joseph Academy',
    neighborhood: 'Race Course',
    city: 'Dehradun',
    state: 'Uttarakhand',
    country: 'India',
    postalCode: '248001',
    latitude: 30.3195,
    longitude: 78.0489,
    phone: '+91 97600 54321',
    email: 'info@motogloss.in',
    coverImage: 'https://images.unsplash.com/photo-1601362840469-51e4d8d58785?auto=format&fit=crop&w=1200&q=80',
    gallery: ['https://images.unsplash.com/photo-1601362840469-51e4d8d58785?auto=format&fit=crop&w=800&q=80'],
    rating: 4.9,
    reviewCount: 88,
    verified: true,
    status: 'active',
    startingPrice: 500,
    features: ['Dust-Free Infrared Bay', 'Certified PPF Installers', 'Customer Lounge & Wi-Fi', 'Pick & Drop Available'],
    schedule: STANDARD_WEEK_SCHEDULE,
    active: true,
    distanceKm: 3.5,
    nextAvailableSlot: 'Today, 5:00 PM',
    pageViewsThisWeek: 140,
    createdAt: '2026-08-04T12:00:00Z',
    updatedAt: '2026-08-22T10:00:00Z',
  },
];

export const INITIAL_SERVICES: Service[] = [
  // Zenith Pickleball Services
  {
    id: 'srv-zpc-single',
    businessId: 'biz-zenith-pickleball',
    name: 'Court Booking (Standard 60 Mins)',
    description: 'Access to 1 tournament-spec cushioned pickleball court for up to 4 players. Includes 4 rental paddles and balls.',
    price: 600,
    originalPrice: 800,
    durationMinutes: 60,
    category: 'Court Booking',
    active: true,
    resourceRequired: true,
    createdAt: '2026-08-05T09:00:00Z',
    updatedAt: '2026-08-05T09:00:00Z',
  },
  {
    id: 'srv-zpc-peak',
    businessId: 'biz-zenith-pickleball',
    name: 'Peak Hours Floodlight Court (90 Mins)',
    description: 'Evening slot under professional LED floodlights for 90 minutes of fast-paced match play.',
    price: 950,
    originalPrice: 1200,
    durationMinutes: 90,
    category: 'Court Booking',
    active: true,
    resourceRequired: true,
    createdAt: '2026-08-05T09:00:00Z',
    updatedAt: '2026-08-05T09:00:00Z',
  },
  {
    id: 'srv-zpc-coaching',
    businessId: 'biz-zenith-pickleball',
    name: '1-on-1 Pro Coaching Clinic (45 Mins)',
    description: 'Personalized drills, third-shot drop mechanics, and dinking strategy with a certified coach.',
    price: 1199,
    originalPrice: 1500,
    durationMinutes: 45,
    category: 'Coaching',
    active: true,
    createdAt: '2026-08-05T09:00:00Z',
    updatedAt: '2026-08-05T09:00:00Z',
  },

  // Smile Studio Services
  {
    id: 'srv-ssd-clean',
    businessId: 'biz-smile-studio',
    name: 'Ultrasonic Teeth Cleaning & Polishing',
    description: 'Painless removal of stubborn calculus, plaque, and surface tea/coffee stains with fluoride polishing paste.',
    price: 800,
    originalPrice: 1200,
    durationMinutes: 45,
    category: 'Preventive Care',
    active: true,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'srv-ssd-consult',
    businessId: 'biz-smile-studio',
    name: 'Comprehensive Dental Consultation + Digital X-Ray',
    description: 'Full oral exam with intra-oral camera imaging and low-radiation digital radiography.',
    price: 500,
    durationMinutes: 30,
    category: 'Diagnostics',
    active: true,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },

  // The Groom Room Services
  {
    id: 'srv-tgr-cut',
    businessId: 'biz-the-groom-room',
    name: 'Signature Precision Haircut & Styling',
    description: 'Personalized consultation, precision clipper fade / scissor work, relaxing shampoo, and matte clay styling.',
    price: 450,
    durationMinutes: 35,
    category: 'Hair Styling',
    active: true,
    createdAt: '2026-08-02T11:00:00Z',
    updatedAt: '2026-08-02T11:00:00Z',
  },
  {
    id: 'srv-tgr-beard',
    businessId: 'biz-the-groom-room',
    name: 'Hot Towel Beard Sculpt & Lineup',
    description: 'Straight-razor edge definition with eucalyptus hot towel steam and nourishing organic cedar beard oil.',
    price: 350,
    durationMinutes: 25,
    category: 'Beard Care',
    active: true,
    createdAt: '2026-08-02T11:00:00Z',
    updatedAt: '2026-08-02T11:00:00Z',
  },

  // QuickCool AC Services
  {
    id: 'srv-qac-serv',
    businessId: 'biz-quickcool-ac',
    name: 'Split AC High-Pressure Jet Service',
    description: 'Complete indoor cooling coil foam wash and outdoor condenser high-pressure jet cleaning.',
    price: 499,
    originalPrice: 799,
    durationMinutes: 50,
    category: 'Maintenance',
    active: true,
    createdAt: '2026-08-03T09:00:00Z',
    updatedAt: '2026-08-03T09:00:00Z',
  },

  // MotoGloss Services
  {
    id: 'srv-mgd-wash',
    businessId: 'biz-motogloss-detailing',
    name: 'Premium Snow Foam Wash & Hydrophobic Seal',
    description: 'Two-bucket scratch-safe snow foam wash, alloy de-ironizer, underbody rinse, and 30-day hydrophobic sealant.',
    price: 500,
    originalPrice: 750,
    durationMinutes: 45,
    category: 'Wash & Shine',
    active: true,
    createdAt: '2026-08-04T12:00:00Z',
    updatedAt: '2026-08-04T12:00:00Z',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-demo-01',
    bookingReference: 'BK-ZPC89A',
    userId: 'usr-customer-gurpreet',
    customerName: 'Gurpreet Singh',
    customerPhone: '+91 98765 43210',
    customerEmail: 'gurpreet@bukkapp.in',
    businessId: 'biz-zenith-pickleball',
    businessName: 'Zenith Pickleball Club',
    businessSlug: 'zenith-pickleball',
    businessAddress: 'Plot 14, Old Rajpur Road, Near Sai Mandir',
    serviceId: 'srv-zpc-single',
    serviceName: 'Court Booking (Standard 60 Mins)',
    servicePrice: 600,
    durationMinutes: 60,
    resourceId: 'res-zpc-c1',
    resourceName: 'Court 1 (Pro Championship)',
    date: '2026-08-25',
    startTime: '18:00',
    endTime: '19:00',
    status: 'confirmed',
    paymentStatus: 'paid_simulated',
    notes: 'Bringing 3 intermediate friends for match play.',
    createdAt: '2026-08-22T09:30:00Z',
    updatedAt: '2026-08-22T09:30:00Z',
  },
  {
    id: 'bk-demo-02',
    bookingReference: 'BK-SSD71X',
    userId: 'usr-customer-gurpreet',
    customerName: 'Gurpreet Singh',
    customerPhone: '+91 98765 43210',
    customerEmail: 'gurpreet@bukkapp.in',
    businessId: 'biz-smile-studio',
    businessName: 'Smile Studio Dental & Implant Center',
    businessSlug: 'smile-studio-dental',
    businessAddress: '42/1 Rajpur Road, Opp. Pacific Mall, Jakhan',
    serviceId: 'srv-ssd-clean',
    serviceName: 'Ultrasonic Teeth Cleaning & Polishing',
    servicePrice: 800,
    durationMinutes: 45,
    date: '2026-08-26',
    startTime: '18:30',
    endTime: '19:15',
    status: 'confirmed',
    paymentStatus: 'paid_simulated',
    notes: 'Routine 6-month checkup.',
    createdAt: '2026-08-22T10:00:00Z',
    updatedAt: '2026-08-22T10:00:00Z',
  },
  {
    id: 'bk-demo-03',
    bookingReference: 'BK-TGR14M',
    userId: 'usr-customer-gurpreet',
    customerName: 'Gurpreet Singh',
    customerPhone: '+91 98765 43210',
    customerEmail: 'gurpreet@bukkapp.in',
    businessId: 'biz-the-groom-room',
    businessName: 'The Groom Room & Barbershop',
    businessSlug: 'the-groom-room',
    businessAddress: '12 General Mahadev Singh Road, Ballupur Chowk',
    serviceId: 'srv-tgr-cut',
    serviceName: 'Signature Precision Haircut & Styling',
    servicePrice: 450,
    durationMinutes: 35,
    date: '2026-08-15',
    startTime: '16:00',
    endTime: '16:35',
    status: 'completed',
    paymentStatus: 'paid_simulated',
    createdAt: '2026-08-14T11:00:00Z',
    updatedAt: '2026-08-15T16:40:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-zpc-01',
    businessId: 'biz-zenith-pickleball',
    userId: 'usr-customer-gurpreet',
    userName: 'Gurpreet Singh',
    rating: 5,
    comment: 'Spectacular courts! The lighting and surface grip are top notch in Dehradun. Booking took 10 seconds on BUKKAPP.',
    serviceName: 'Court Booking (Standard 60 Mins)',
    createdAt: '2026-08-18T19:00:00Z',
    businessReply: {
      comment: 'Thank you Gurpreet! We look forward to seeing you and your crew on Court 1 again soon.',
      createdAt: '2026-08-18T20:15:00Z',
    },
  },
  {
    id: 'rev-ssd-01',
    businessId: 'biz-smile-studio',
    userId: 'usr-customer-gurpreet',
    userName: 'Gurpreet Singh',
    rating: 5,
    comment: 'Dr. Arjun is remarkably gentle and transparent. Zero waiting time when booking the slot.',
    serviceName: 'Ultrasonic Teeth Cleaning & Polishing',
    createdAt: '2026-08-10T14:30:00Z',
    businessReply: {
      comment: 'Thank you for trusting Smile Studio with your dental care!',
      createdAt: '2026-08-10T16:00:00Z',
    },
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'usr-owner-rahul',
    businessId: 'biz-zenith-pickleball',
    type: 'booking_created',
    title: 'New Booking Received',
    message: 'Gurpreet Singh booked Court 1 for Court Booking (Standard 60 Mins) on Aug 25 at 6:00 PM.',
    read: false,
    createdAt: '2026-08-22T09:30:00Z',
    link: '/business/bookings',
  },
  {
    id: 'notif-2',
    userId: 'usr-owner-rahul',
    businessId: 'biz-zenith-pickleball',
    type: 'business_approved',
    title: 'Listing Verified and Live',
    message: 'Zenith Pickleball Club has been verified by the BUKKAPP Operations Team.',
    read: true,
    createdAt: '2026-08-06T12:00:00Z',
    link: '/business/dashboard',
  },
  {
    id: 'notif-3',
    userId: 'usr-customer-gurpreet',
    type: 'changes_requested',
    businessId: 'biz-jakhan-crossfit',
    title: 'Changes Requested on Your Listing',
    message: 'Please update your opening hours and upload at least 2 photos of the gym interior before publication.',
    read: false,
    createdAt: '2026-08-20T11:00:00Z',
    link: '/business/profile',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    actorUserId: 'usr-admin-bukkapp',
    actorName: 'BUKKAPP Admin',
    action: 'business_approved',
    entityType: 'business',
    entityId: 'biz-zenith-pickleball',
    metadata: { businessName: 'Zenith Pickleball Club', status: 'active', verified: true },
    createdAt: '2026-08-06T12:00:00Z',
  },
  {
    id: 'aud-2',
    actorUserId: 'usr-admin-bukkapp',
    actorName: 'BUKKAPP Admin',
    action: 'changes_requested',
    entityType: 'business',
    entityId: 'biz-jakhan-crossfit',
    metadata: { reason: 'Please update your opening hours and upload at least 2 photos of the gym interior.' },
    createdAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'aud-3',
    actorUserId: 'usr-admin-bukkapp',
    actorName: 'BUKKAPP Admin',
    action: 'business_suspended',
    entityType: 'business',
    entityId: 'biz-city-glamour',
    metadata: { reason: 'Repeated customer complaints regarding off-platform pricing discrepancies.' },
    createdAt: '2026-08-21T18:00:00Z',
  },
];
